services:
  # PHP Service
  php:
    image: php:fpm
    container_name: prarambhify-php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - prarambhify-network

  # Database Server
  postgres:
    image: postgres:latest
    container_name: prarambhify-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: prarambhify
      POSTGRES_USER: prarambhify
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prarambhify-network

  # Nginx Server
  nginx:
    image: nginx:latest
    container_name: prarambhify-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - prarambhify-network

volumes:
  db-data:


networks:
  prarambhify-network:
    driver: bridge
