# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: prarambhify_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - prarambhify_net

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: prarambhify_php
    volumes:
      - ./src:/var/www/html
    networks:
      - prarambhify_net

  postgres:
    image: postgres:17
    container_name: prarambhify_postgres
    environment:
      POSTGRES_DB: prarambh
      POSTGRES_USER: prarambhify
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prarambhify_net

networks:
  prarambhify_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
