version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prarambhify-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
    networks:
      - prarambhify-network

networks:
  prarambhify-network:
    driver: bridge



