# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: pramabhify_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - pramabhify_net

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pramabhify_php
    volumes:
      - ./src:/var/www/html
    networks:
      - pramabhify_net

  postgres:
    image: postgres:15
    container_name: pramabhify_postgres
    environment:
      POSTGRES_DB: pramabhify
      POSTGRES_USER: pramabhify
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pramabhify_net

networks:
  pramabhify_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local